services:
  nextjs:
    build: .
    container_name: nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && npm run start"
